<?php
/**
 * @file
 * Code for the Stanford Exhibition Space feature.
 */

include_once 'stanford_exhibition_space.features.inc';

/**
 * Implements hook_block_info().
 */
function stanford_exhibition_space_block_info() {

  $blocks['ses_two_links'] = array(
    'info'    => t('Exhibition Space On View Now Exhbition Links'),
    'cache'   => DRUPAL_CACHE_PER_PAGE,
  );

  return $blocks;
}


/**
 * Returns the see upcoming exhibitions and see past exhibitions links.
 * @return [type] [description]
 */
function stanford_exhibition_space_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'ses_two_links':

    $output = "";
    $a0 = arg(0);
    $a1 = arg(1);

    if ($a0 == "node" && is_numeric($a1)) {
      $node = node_load($a1);
    }

    if (!isset($node->nid)) { break; }

    // See upcoming link.
    $output .= "<p>" . l('See upcoming exhibitions', 'exhibition-space/space/' . $node->nid, array('attributes' => array('rel' => 'nofollow', 'class' => 'more-link'))) . "</p>";
    // See past.
    $output .= "<p>" . l('See past exhibitions', 'exhibition-space/past-space/' . $node->nid, array('attributes' => array('rel' => 'nofollow', 'class' => 'more-link'))) . "</p>";

    $block['content'] = $output;

    break;
  }

  return $block;
}

/**
 * Alter the exhibition by space to change the title to be the exhibition space title
 * @param  [type] $view [description]
 * @return [type]       [description]
 */
function stanford_exhibition_space_views_post_render(&$view) {

  // eg: /exhibition-space/space/1549
  if ($view->name == "stanford_exhibition_spaces" && $view->current_display == 'exhibition_by_space') {
    $a2 = arg(2);
    if (is_numeric($a2)) {
      $space = node_load($a2);
      if (isset($space->title)) {
        $title = $space->title . ' Upcoming Exhibitions';
        $view->set_title($title);
      }
    }
  }
  // eg: /exhibition-space/past-space/1549
  if ($view->name == "stanford_exhibition_spaces" && $view->current_display == 'past_exh_by_space') {
    $a2 = arg(2);
    if (is_numeric($a2)) {
      $space = node_load($a2);
      if (isset($space->title)) {
        $title = $space->title . ' Past Exhibitions';
        $view->set_title($title);
      }
    }
  }

}

